name: Java CI

env:
    JDK_CURRENT: 17
    DISTRIBUTION: zulu

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

permissions:
  contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
            - name: Set up JDK
              uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
              with:
                  java-version: ${{ env.JDK_CURRENT }}
                  distribution: ${{ env.DISTRIBUTION }}
            - name: Cache Maven dependencies
              uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5
              with:
                  path: ~/.m2/repository
                  key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
                  restore-keys: ${{ runner.os }}-m2
            - name: Build with Maven
              run: mvn -B clean install

    deploy:
        if: startsWith(github.ref, 'refs/heads/')
        runs-on: ubuntu-latest
        needs: [build]
        steps:
            - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
            - name: Set up JDK
              uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
              with:
                  java-version: ${{ env.JDK_CURRENT }}
                  server-id: central-portal-snapshots
                  server-username: MAVEN_USERNAME
                  server-password: MAVEN_PASSWORD
                  distribution: ${{ env.DISTRIBUTION }}
            - name: Deploy to Sonatype
              run: mvn -B -DskipTests deploy
              env:
                  MAVEN_USERNAME: ${{ secrets.SONATYPE_USER }}
                  MAVEN_PASSWORD: ${{ secrets.SONATYPE_PWD }}

    doc:
        if: startsWith(github.ref, 'refs/heads/')
        runs-on: ubuntu-latest
        needs: [deploy]
        steps:
            - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
            - name: Set up JDK
              uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
              with:
                  java-version: ${{ env.JDK_CURRENT }}
                  distribution: ${{ env.DISTRIBUTION }}
            - name: Generate and push doc
              run: chmod -R 777 ./ci/*.sh && ./ci/push-doc-to-gh-pages.sh
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
