name: Java CI

env:
    JDK_CURRENT: 17
    DISTRIBUTION: zulu

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

permissions:
  contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
            - name: Set up JDK
              uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3
              with:
                  java-version: ${{ env.JDK_CURRENT }}
                  distribution: ${{ env.DISTRIBUTION }}
            - name: Cache Maven dependencies
              uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3
              with:
                  path: ~/.m2
                  key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
                  restore-keys: ${{ runner.os }}-m2
            - name: Build with Maven
              run: mvn -B clean install

    deploy:
        if: startsWith(github.ref, 'refs/heads/')
        runs-on: ubuntu-latest
        needs: [build]
        steps:
            - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
            - name: Set up JDK
              uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3
              with:
                  java-version: ${{ env.JDK_CURRENT }}
                  server-id: sonatype-nexus-snapshots
                  server-username: MAVEN_USERNAME
                  server-password: MAVEN_PASSWORD
                  distribution: ${{ env.DISTRIBUTION }}
            - name: Deploy to Sonatype
              run: mvn -B -DskipTests deploy
              env:
                  MAVEN_USERNAME: ${{ secrets.SONATYPE_USER }}
                  MAVEN_PASSWORD: ${{ secrets.SONATYPE_PWD }}

    doc:
        if: startsWith(github.ref, 'refs/heads/')
        runs-on: ubuntu-latest
        needs: [deploy]
        steps:
            - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
            - name: Set up JDK
              uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3
              with:
                  java-version: ${{ env.JDK_CURRENT }}
                  distribution: ${{ env.DISTRIBUTION }}
            - name: Generate and push doc
              run: chmod -R 777 ./ci/*.sh && ./ci/push-doc-to-gh-pages.sh
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
