name: Java CI

env:
    JDK_CURRENT: 17
    DISTRIBUTION: zulu

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

permissions:
  contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
            - name: Set up JDK
              uses: actions/setup-java@a18c333f3f14249953dab3e186e5e21bf3390f1d # tag=v3
              with:
                  java-version: ${{ env.JDK_CURRENT }}
                  distribution: ${{ env.DISTRIBUTION }}
            - name: Cache Maven dependencies
              uses: actions/cache@56461b9eb0f8438fd15c7a9968e3c9ebb18ceff1 # tag=v3
              with:
                  path: ~/.m2
                  key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
                  restore-keys: ${{ runner.os }}-m2
            - name: Build with Maven
              run: mvn -B clean install

    deploy:
        if: startsWith(github.ref, 'refs/heads/')
        runs-on: ubuntu-latest
        needs: [build]
        steps:
            - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
            - name: Set up JDK
              uses: actions/setup-java@a18c333f3f14249953dab3e186e5e21bf3390f1d # tag=v3
              with:
                  java-version: ${{ env.JDK_CURRENT }}
                  server-id: sonatype-nexus-snapshots
                  server-username: MAVEN_USERNAME
                  server-password: MAVEN_PASSWORD
                  distribution: ${{ env.DISTRIBUTION }}
            - name: Deploy to Sonatype
              run: mvn -B -DskipTests deploy
              env:
                  MAVEN_USERNAME: ${{ secrets.SONATYPE_USER }}
                  MAVEN_PASSWORD: ${{ secrets.SONATYPE_PWD }}

    doc:
        if: startsWith(github.ref, 'refs/heads/')
        runs-on: ubuntu-latest
        needs: [deploy]
        steps:
            - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
            - name: Set up JDK
              uses: actions/setup-java@a18c333f3f14249953dab3e186e5e21bf3390f1d # tag=v3
              with:
                  java-version: ${{ env.JDK_CURRENT }}
                  distribution: ${{ env.DISTRIBUTION }}
            - name: Generate and push doc
              run: chmod -R 777 ./ci/*.sh && ./ci/push-doc-to-gh-pages.sh
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
